services:
    pgsql:
        container_name: pgsql
        image: postgres:17-bookworm
        restart: unless-stopped
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - ./docker/pgsql/data:/var/lib/postgresql/data
        networks:
            - simakara-tryout
    mailpit:
      container_name: mailpit
      image: axllent/mailpit:latest
      restart: unless-stopped
      ports:
        - "8025:8025"
        - "1025:1025"
      environment:
        MP_MAX_MESSAGES: 100
        MP_DATABASE: /data/mailpit.db
        MP_SMTP_AUTH_ACCEPT_ANY: 1
        MP_SMTP_AUTH_ALLOW_INSECURE: 1
      volumes:
        - ./docker/mailpit/data:/data
      networks:
        - simakara-tryout

networks:
    simakara-tryout:
        name: simakara-tryout
        driver: bridge
